name: Complex workflow
on: push

jobs:
 ubuntu:
   runs-on: ubuntu-latest
   steps:
    - run: date
    - name: Python Syntax Checker
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0   
 
 windows: 
  runs-on: windows-latest
  steps:
    - run: date

 macos: 
  runs-on: macos-latest
  steps:
    - run: date

 depends:
  needs: [ubuntu, windows,macos]
  runs-on: macos-latest
  steps:
    - run: date
